# Generated by Django 5.0.6 on 2024-05-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('text', models.CharField(max_length=120, verbose_name='Описание')),
                ('date', models.DateField(auto_now=True, verbose_name='Время создание')),
                ('date_db', models.DateTimeField(auto_now_add=True, verbose_name='Время создание')),
                ('slug', models.SlugField(blank=True, max_length=20, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Посты сайта',
                'verbose_name_plural': 'Посты сайта',
                'ordering': ['-date_db'],
            },
        ),
    ]
